export type TenancyPayload = {
  tenant: string;
  tenant_id_no?: string;
  tenant_phone?: string;
  tenant_email?: string;
  landlord: string;
  landlord_id_no?: string;
  landlord_phone?: string;
  landlord_email?: string;
  property: string;
  unit_no?: string;
  property_address?: string;
  property_type?: string;
  monthly_rental: number;
  security_deposit: number;
  utility_deposit: number;
  access_card_deposit: number;
  car_park_remote_deposit: number;
  commencement_date: string | null;
  expiry_date: string | null;
  renewal_option?: string;
  notice_period?: string;
  renewal_reminder?: string | null;
  signed_ta?: string;
  renewal_history?: string;
  special_clauses?: string;
  notes?: string;
  status?: string;
};

export type CollectionPayload = {
  tenancy_id: string;
  collection_month: string;
  due_date: string;
  rental_amount: number;
  tnb_amount: number;
  water_amount: number;
  iwk_amount: number;
  wifi_amount: number;
  aircond_amount: number;
  other_charges: number;
  amount_paid: number;
  payment_status: 'paid' | 'partial' | 'outstanding' | 'overdue';
  payment_date?: string | null;
  payment_method?: string;
  payment_reference?: string;
  notes?: string;
  payment_history?: unknown[];
};
