export const commercialResources = {
  companies: { table: 'commercial_companies', search: ['legal_name', 'registration_number', 'industry', 'notes'], fields: ['legal_name','registration_number','country','headquarters','industry','business_category','website','company_status','expansion_status','target_countries','target_cities','notes','source','tags','assigned_user_id','next_follow_up','status','metadata'] },
  brands: { table: 'commercial_brands', search: ['brand_name', 'notes'], fields: ['company_id','brand_name','business_category','expansion_status','target_countries','target_cities','website','notes','assigned_user_id','status','metadata'] },
  contacts: { table: 'commercial_contacts', search: ['full_name', 'phone', 'whatsapp_number', 'email', 'job_title', 'notes'], fields: ['company_id','brand_id','full_name','job_title','department','phone','whatsapp_number','email','preferred_language','nationality','country','decision_maker_level','influence_level','communication_preference','last_contacted_date','next_follow_up','notes','assigned_user_id','status','confidentiality_level','metadata'] },
  requirements: { table: 'commercial_requirements', search: ['title', 'requirement_type', 'target_building', 'notes'], fields: ['title','company_id','brand_id','contact_id','requirement_type','property_category','transaction_type','preferred_locations','excluded_locations','target_building','min_built_up','max_built_up','min_land_area','max_land_area','frontage_requirement','ceiling_height_requirement','floor_preference','corner_preference','ground_floor_required','drive_through_required','parking_requirement','loading_bay_required','power_requirement','three_phase_required','exhaust_required','grease_trap_required','gas_required','water_required','signage_required','outdoor_area_required','swimming_pool_required','kitchen_ready_required','commercial_zoning_required','licence_requirement','halal_requirement','target_rental','max_rental','target_purchase_price','max_purchase_price','preferred_tenancy_term','commencement_target','urgency','confidentiality_level','source','assigned_user_id','status','rejection_reasons','notes','expiry_date','next_follow_up','metadata'] },
  listings: { table: 'commercial_listings', search: ['title', 'property_name', 'property_type', 'city', 'area', 'address', 'landlord_name', 'notes'], fields: ['title','property_name','property_type','transaction_type','state','city','area','address','concealed_address','latitude','longitude','built_up','land_area','asking_rental','asking_sale_price','negotiable','maintenance_fee','frontage','ceiling_height','floor_level','corner','ground_floor','parking','loading_bay','three_phase_electricity','electrical_capacity','exhaust','grease_trap','gas','water','signage_exposure','main_road_frontage','outdoor_area','swimming_pool','commercial_zoning','current_use','allowed_businesses','prohibited_businesses','furnished_status','renovation_condition','availability_date','landlord_name','landlord_contact','listing_agent','co_broke_status','source','confidentiality_level','exact_location_visibility','photo_paths','document_paths','notes','assigned_user_id','status','expiry_date','last_verified_date','metadata'] },
  matches: { table: 'commercial_matches', search: ['explanation', 'feedback', 'rejection_reason'], fields: ['requirement_id','listing_id','overall_score','category_scores','matched_criteria','missing_criteria','hard_conflicts','warnings','recommendation_level','explanation','shortlist_status','rejection_reason','feedback','ai_explanation','ai_model','ai_generated_at','assigned_user_id','status','metadata'] },
  deals: { table: 'commercial_deals', search: ['title', 'landlord_name', 'co_broke_agent', 'next_action', 'notes'], fields: ['title','company_id','brand_id','contact_id','requirement_id','listing_id','landlord_name','co_broke_agent','deal_value','expected_commission','commission_share','stage','probability','next_action','next_follow_up','target_close_date','actual_close_date','loss_reason','notes','assigned_user_id','status','metadata'] },
  viewings: { table: 'commercial_viewings', search: ['location', 'client_feedback', 'landlord_feedback'], fields: ['listing_id','requirement_id','viewing_date','attendees','location','viewing_status','client_feedback','landlord_feedback','rejection_reason','next_step','follow_up_date','photo_paths','document_paths','assigned_user_id','status','metadata'] },
  proposals: { table: 'commercial_proposals', search: ['internal_notes', 'client_notes'], fields: ['requirement_id','proposed_date','proposal_language','internal_notes','client_notes','response_date','shortlist_result','assigned_user_id','status','metadata'] },
  followups: { table: 'commercial_followups', search: ['note', 'draft_text', 'follow_up_type'], fields: ['company_id','contact_id','requirement_id','listing_id','deal_id','proposal_id','viewing_id','follow_up_type','due_at','completed_at','priority','note','draft_text','assigned_user_id','status','metadata'] }
} as const;

export type CommercialResource = keyof typeof commercialResources;

export function commercialResource(value: string) {
  return Object.prototype.hasOwnProperty.call(commercialResources, value) ? value as CommercialResource : null;
}

export function allowedCommercialChanges(resource: CommercialResource, input: Record<string, unknown>) {
  const fields = new Set<string>(commercialResources[resource].fields);
  return Object.fromEntries(Object.entries(input).filter(([key]) => fields.has(key) && key !== 'workspace_id' && key !== 'created_by'));
}

