'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Plus, RefreshCw, X } from 'lucide-react';
import AppNav from '../components/AppNav';
import { usePortalLanguage } from '../components/usePortalLanguage';
import { crmEnumLabel, getCrmCopy } from '../../lib/i18n/crm';
import { availableCrmStageTransitions, CRM_PIPELINE_STAGES, crmStageLabel, crmStageTone, type CrmPipelineStage } from '../../lib/crm/pipeline';
import type { WorkspaceRole } from '../../lib/rbac/permissions';

type Contact={id:string;full_name?:string;company_name?:string};
type Deal={id:string;deal_number:string;title:string;transaction_type:string;stage:CrmPipelineStage;deal_value?:number|null;expected_commission?:number|null;probability?:number|null;assigned_user_id?:string|null;contact?:Contact|null;updated_at:string};
function name(contact?:Contact|null){return contact?.full_name||contact?.company_name||'—';}
function money(value?:number|null){return value===null||value===undefined?'—':new Intl.NumberFormat('en-MY',{style:'currency',currency:'MYR',maximumFractionDigits:0}).format(value);}

export default function DealsWorkspace({initialRole}:{initialRole:WorkspaceRole}){
  const language=usePortalLanguage();const c=getCrmCopy(language);
  const [rows,setRows]=useState<Deal[]>([]);const [contacts,setContacts]=useState<Contact[]>([]);const [role,setRole]=useState(initialRole);const [userId,setUserId]=useState('');
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);
  const canWrite=['owner','admin','agent'].includes(role);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [dealsResponse,contextResponse]=await Promise.all([fetch('/api/crm/deals?pageSize=100',{cache:'no-store'}),fetch('/api/crm/context',{cache:'no-store'})]);const dealsPayload=await dealsResponse.json() as {success:boolean;rows:Deal[];role:WorkspaceRole;userId:string};const context=await contextResponse.json() as {success:boolean;contacts:Contact[]};if(!dealsResponse.ok||!dealsPayload.success)throw new Error();setRows(dealsPayload.rows);setRole(dealsPayload.role);setUserId(dealsPayload.userId);if(contextResponse.ok&&context.success)setContacts(context.contacts);}catch{setError('request-failed');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{if(new URLSearchParams(window.location.search).get('action')==='new-deal')setOpen(true);},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const response=await fetch('/api/crm/deals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget).entries()))});if(response.ok){setOpen(false);event.currentTarget.reset();await load();}else setError('request-failed');setSaving(false);}
  async function advance(deal:Deal){const next=availableCrmStageTransitions(deal.stage).find(stage=>stage!=='LOST');if(!next)return;const response=await fetch('/api/crm/deals',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deal.id,stage:next})});if(response.ok)void load();else setError('request-failed');}
  async function lost(deal:Deal){const reason=window.prompt(language==='zh'?'请输入流失原因':'Reason this deal was lost');if(!reason)return;const response=await fetch('/api/crm/deals',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deal.id,stage:'LOST',lostReason:reason})});if(response.ok)void load();else setError('request-failed');}
  const grouped=useMemo(()=>CRM_PIPELINE_STAGES.map(stage=>({stage,rows:rows.filter(row=>row.stage===stage)})),[rows]);
  return <main className="command-shell crm-shell"><header className="command-header crm-header"><div><p className="eyebrow">NEXORA CORE</p><h1>{language==='zh'?'交易流程':'Deal Journey'}</h1><p className="header-copy">{language==='zh'?'从询盘到成交及售后服务，使用统一且可审计的阶段推进交易。':'Move rental, subsale, project, and commercial deals through one auditable journey.'}</p></div><AppNav activePage="deals">{canWrite&&<button className="crm-primary" onClick={()=>setOpen(true)}><Plus size={16}/>{language==='zh'?'新建交易':'New deal'}</button>}</AppNav></header>
  <section className="crm-toolbar"><div className="deal-summary"><strong>{rows.length}</strong><span>{language==='zh'?'活跃交易':'active deals'}</span><strong>{money(rows.reduce((sum,row)=>sum+Number(row.deal_value||0),0))}</strong><span>{language==='zh'?'流程价值':'pipeline value'}</span></div><button className="crm-icon-button" onClick={()=>void load()}><RefreshCw size={16}/></button></section>
  {!canWrite&&<div className="crm-read-only">{c.readOnly}</div>}{error&&<div className="crm-alert">{c.unavailable}</div>}{loading?<div className="crm-state">{c.loading}</div>:rows.length===0?<div className="crm-state"><strong>{language==='zh'?'暂无交易。':'No active deals yet.'}</strong>{canWrite&&<button className="crm-primary" onClick={()=>setOpen(true)}>{language==='zh'?'新建首笔交易':'Create first deal'}</button>}</div>:<div className="crm-kanban">{grouped.map(group=><section className="crm-kanban-column" key={group.stage}><header><span className={`crm-badge ${crmStageTone(group.stage)}`}>{crmStageLabel(group.stage,language)}</span><strong>{group.rows.length}</strong></header>{group.rows.map(deal=><article className="deal-kanban-card" key={deal.id}><strong>{deal.title}</strong><span>{deal.deal_number} · {name(deal.contact)}</span><b>{money(deal.deal_value)}</b><small>{crmEnumLabel(deal.transaction_type,language)}</small>{canWrite&&(role!=='agent'||deal.assigned_user_id===userId)&&<div><button disabled={!availableCrmStageTransitions(deal.stage).some(stage=>stage!=='LOST')} onClick={()=>void advance(deal)}>{c.advanceStage}<ArrowRight size={13}/></button>{deal.stage!=='LOST'&&<button className="danger" onClick={()=>void lost(deal)}>{c.markLost}</button>}</div>}</article>)}</section>)}</div>}
  {open&&<div className="crm-modal"><form onSubmit={event=>void submit(event)}><header><h2>{language==='zh'?'新建交易':'New deal'}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></header>{contacts.length===0?<div className="crm-duplicate"><strong>{language==='zh'?'请先添加客户。':'Add a client before creating a deal.'}</strong><a href="/contacts?action=new-contact">{language==='zh'?'添加客户':'Add client'} →</a></div>:<div className="crm-form-grid"><label className="wide"><span>{c.title}</span><input name="title" required/></label><label><span>{c.client}</span><select name="contactId" required><option value="">—</option>{contacts.map(contact=><option value={contact.id} key={contact.id}>{name(contact)}</option>)}</select></label><label><span>{c.transactionType}</span><select name="transactionType">{['rent','buy','subsale','commercial_rent','commercial_buy','land','new_project'].map(value=><option key={value} value={value}>{crmEnumLabel(value,language)}</option>)}</select></label><label><span>{language==='zh'?'交易金额':'Deal value'}</span><input name="dealValue" type="number" min="0"/></label><label><span>{language==='zh'?'预计佣金':'Expected commission'}</span><input name="expectedCommission" type="number" min="0"/></label><label className="wide"><span>{c.notes}</span><textarea name="notes" rows={3}/></label></div>}<footer><button type="button" onClick={()=>setOpen(false)}>{c.cancel}</button>{contacts.length>0&&<button className="crm-primary" disabled={saving}>{saving?c.saving:c.save}</button>}</footer></form></div>}</main>;
}
